sudo: required
services:
  - docker
language: node_js
node_js:
  - '6'
  - '4'
before_script:
  - 'npm run setup-couchbase'
  - ./scripts/wait-for-couchbase.sh
after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls'
